datasets:
  TC:
    data_type: images

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url:  /content/MiniGPT-Pancreas2.0/datasets/TC/annotations/TC_train.json
          storage:  /content/MiniGPT-Pancreas2.0/datasets/TC/annotations/TC_train.json
      images:
          storage: /content/MiniGPT-Pancreas2.0/datasets/TC/slices
