model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: True
  prompt_template: '[INST] {} [/INST]'
  llama_model: "/content/Llama-2-7b-chat-hf/"
  ckpt: "/content/MiniGPT-Pancreas2.0/output/minigptv2_finetune/20260501222/checkpoint_14.pth"
  ckpt_dir: "/content/MiniGPT-Pancreas2.0/output/minigptv2_finetune/20260501222/"
  lora_r: 64
  lora_alpha: 16

datasets:
  TC:
    build_info:
      # Keep this as the full path to the training file for the builder
      ann_storage: "/content/MiniGPT-Pancreas2.0/datasets/TC/annotations/TC_train.json"
      vis_storage: "/content/MiniGPT-Pancreas2.0/datasets/TC/slices"
    text_processor:
      train:
        name: "blip_caption"
      eval:
        name: "blip_caption"
    vis_processor:
      train:
        image_size: 448
        name: "blip2_image_eval"
      eval:
        image_size: 448
        name: "blip2_image_eval"

evaluation_datasets:
  TC:
    # IMPORTANT: Set this to the FOLDER path only
    eval_file_path: "/content/MiniGPT-Pancreas2.0/datasets/TC/annotations"
    img_path: "/content/MiniGPT-Pancreas2.0/datasets/TC/slices"
    max_new_tokens: 20
    batch_size: 10
  MSD_tumor_detection:
    eval_file_path: /content/MiniGPT-Pancreas2.0/datasets/MSD/annotations
    img_path: /content/MiniGPT-Pancreas2.0/datasets/MSD/slices
    max_new_tokens: 20
    batch_size: 16

run:
  task: vqa
  name: minigptv2_evaluation
  save_path: "/content/MiniGPT-Pancreas2.0/eval_results"
  device: "cuda"
